name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Fetch Dependabot Metadata
        id: meta
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:
          token: ${{ secrets.GITHUB_TOKEN }}     
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
